### ISSUE TITLE
uninitialized constant GoodJob::Process

### ISSUE THREAD

**Issue by gap777** [bensheldon/good_job#1006]
Saw this in logs after updating to 3.15.14

```
[GoodJob] Notifier errored: NameError: uninitialized constant GoodJob::Process

15:44:27 web.1  |  ["/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/good_job-3.15.14/lib/good_job/notifier/process_heartbeat.rb:24:in `refresh_process'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:400:in `block in make_lambda'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:686:in `catch'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:686:in `block in default_terminator'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:200:in `block in halting'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:595:in `block in invoke_before'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:595:in `each'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:595:in `invoke_before'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.6/lib/active_support/callbacks.rb:106:in `run_callbacks'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/good_job-3.15.14/lib/good_job/notifier.rb:192:in `block (2 levels) in listen'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/good_job-3.15.14/lib/good_job/notifier.rb:235:in `with_connection'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/good_job-3.15.14/lib/good_job/notifier.rb:178:in `block in listen'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:in `block in ns_post_task'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'", "/Users/gap/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'"]

```

**Comment by bensheldon** [comment]
@gap777 thanks for opening this issue! I think I see the problem: I'm missing a `Rails.application.executor.wrap` around that newly introduced `GoodJob::Process` reference. I'll have a patch momentarily.

**Comment by bensheldon** [comment]
I just released the fix for this. Thank you again! https://github.com/bensheldon/good_job/releases/tag/v3.16.1
