### ISSUE TITLE
Notifier errored: ArgumentError: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by henrylawson** [bensheldon/good_job#1016]
I am attempting to migrate an existing rails codebase from Sidekiq to good_job.

_Gemfile.lock_
```
rails (6.1.7.4)
good_job (3.16.3)
pg (1.5.3)
```

After following the basic install steps in the README, I am consistently getting an error when trying to run the external process and when attempting to visit the mounted dashboard.

I am not really sure where to go from here. I've tried dropping down good_job gem versions to 3.14, and I still get the same error. Any advice would be appreciated!

_config/initializers/good_job.rb_
```
ActionMailer::MailDeliveryJob.retry_on StandardError,
                                       wait: :exponentially_longer,
                                       attempts: Float::INFINITY

Rails.application.configure do
  config.good_job.preserve_job_records = true
  config.good_job.execution_mode = :external
  config.good_job.queues = '+critical,default,mailers,low,*'
  config.good_job.poll_interval = 15 # seconds
  config.good_job.shutdown_timeout = 20 # seconds
end
```

When visiting the dashboard: 

_logs_
```
ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    2: <%= render 'good_job/shared/chart', chart_data: GoodJob::ScheduledByQueueChart.new(@filter).data %>
    3:
    4: <div data-live-poll-region="jobs-table">
    5:   <%= render 'good_job/jobs/table', jobs: @filter.records, filter: @filter %>
    6:   <% if @filter.records.present? %>
    7:     <nav aria-label="<%= t ".job_pagination" %>" class="mt-3">
    8:       <ul class="pagination">
good_job (3.16.3) app/models/concerns/good_job/lockable.rb:76:in `block (2 levels) in <module:Lockable>'
activerecord (6.1.7.4) lib/active_record/relation.rb:411:in `instance_exec'
activerecord (6.1.7.4) lib/active_record/relation.rb:411:in `block in _exec_scope'
activerecord (6.1.7.4) lib/active_record/relation.rb:804:in `_scoping'
activerecord (6.1.7.4) lib/active_record/relation.rb:411:in `_exec_scope'
activerecord (6.1.7.4) lib/active_record/scoping/named.rb:176:in `block in scope'
activerecord (6.1.7.4) lib/active_record/relation/delegation.rb:67:in `block in joins_advisory_locks'
activerecord (6.1.7.4) lib/active_record/relation.rb:406:in `block in scoping'
activerecord (6.1.7.4) lib/active_record/relation.rb:804:in `_scoping'
activerecord (6.1.7.4) lib/active_record/relation.rb:406:in `scoping'
activerecord (6.1.7.4) lib/active_record/relation/delegation.rb:67:in `joins_advisory_locks'
good_job (3.16.3) app/models/concerns/good_job/lockable.rb:94:in `block (2 levels) in <module:Lockable>'
activerecord (6.1.7.4) lib/active_record/relation.rb:411:in `instance_exec'
activerecord (6.1.7.4) lib/active_record/relation.rb:411:in `block in _exec_scope'
activerecord (6.1.7.4) lib/active_record/relation.rb:804:in `_scoping'
activerecord (6.1.7.4) lib/active_record/relation.rb:411:in `_exec_scope'
activerecord (6.1.7.4) lib/active_record/scoping/named.rb:176:in `block in scope'
activerecord (6.1.7.4) lib/active_record/relation/delegation.rb:67:in `block in includes_advisory_locks'
activerecord (6.1.7.4) lib/active_record/relation.rb:406:in `block in scoping'
activerecord (6.1.7.4) lib/active_record/relation.rb:804:in `_scoping'
activerecord (6.1.7.4) lib/active_record/relation.rb:406:in `scoping'
activerecord (6.1.7.4) lib/active_record/relation/delegation.rb:67:in `includes_advisory_locks'
good_job (3.16.3) app/filters/good_job/jobs_filter.rb:54:in `query_for_records'
good_job (3.16.3) app/filters/good_job/base_filter.rb:18:in `records'
good_job (3.16.3) app/views/good_job/jobs/index.html.erb:5
actionview (6.1.7.4) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.7.4) lib/action_view/base.rb:247:in `_run'
actionview (6.1.7.4) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
actionview (6.1.7.4) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.7.4) lib/action_view/template.rb:152:in `render'
actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
activesupport (6.1.7.4) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.7.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.7.4) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
activesupport (6.1.7.4) lib/active_support/notifications.rb:205:in `instrument'
actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
actionview (6.1.7.4) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.1.7.4) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.1.7.4) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.1.7.4) lib/action_view/base.rb:273:in `in_rendering_context'
actionview (6.1.7.4) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.1.7.4) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.1.7.4) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.1.7.4) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.1.7.4) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.1.7.4) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.1.7.4) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.1.7.4) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
activesupport (6.1.7.4) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.1.7.4) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (6.1.7.4) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
activerecord (6.1.7.4) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.1.7.4) lib/action_controller/metal/instrumentation.rb:45:in `render'
actionpack (6.1.7.4) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (6.1.7.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
<internal:kernel>:90:in `tap'
actionpack (6.1.7.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.7.4) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.7.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.7.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.7.4) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
i18n (1.14.1) lib/i18n.rb:322:in `with_locale'
good_job (3.16.3) app/controllers/good_job/application_controller.rb:37:in `use_good_job_locale'
activesupport (6.1.7.4) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
actiontext (6.1.7.4) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (6.1.7.4) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
activesupport (6.1.7.4) lib/active_support/callbacks.rb:126:in `instance_exec'
activesupport (6.1.7.4) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
activesupport (6.1.7.4) lib/active_support/callbacks.rb:137:in `run_callbacks'
actionpack (6.1.7.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.7.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.7.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.7.4) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.7.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.7.4) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.7.4) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.7.4) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.7.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.7.4) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.7.4) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.7.4) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.7.4) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.7.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.7.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.7.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.7.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.7.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.7.4) lib/action_dispatch/routing/route_set.rb:842:in `call'
railties (6.1.7.4) lib/rails/engine.rb:539:in `call'
railties (6.1.7.4) lib/rails/railtie.rb:207:in `public_send'
railties (6.1.7.4) lib/rails/railtie.rb:207:in `method_missing'
actionpack (6.1.7.4) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
actionpack (6.1.7.4) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (6.1.7.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.7.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.7.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.7.4) lib/action_dispatch/routing/route_set.rb:842:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/static.rb:24:in `call'
bullet (6.1.5) lib/bullet/rack.rb:12:in `call'
rack (2.2.7) lib/rack/content_length.rb:17:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.7) lib/rack/etag.rb:27:in `call'
rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.7) lib/rack/head.rb:12:in `call'
actionpack (6.1.7.4) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.7.4) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/cookies.rb:697:in `call'
activerecord (6.1.7.4) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.7.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.7.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
lograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (6.1.7.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.7.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.7.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.7.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.7.4) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.7) lib/rack/method_override.rb:24:in `call'
rack (2.2.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.7.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.7.4) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
rack-mini-profiler (3.1.0) lib/mini_profiler.rb:260:in `call'
webpacker (5.4.4) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.7.6) lib/rack/proxy.rb:87:in `call'
railties (6.1.7.4) lib/rails/engine.rb:539:in `call'
puma (5.6.6) lib/puma/configuration.rb:252:in `call'
puma (5.6.6) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.6) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.6) lib/puma/request.rb:76:in `handle_request'
puma (5.6.6) lib/puma/server.rb:443:in `process_client'
puma (5.6.6) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

When attempting to run the external process `bundle exec good_job`

_logs_
```
[GoodJob] Notifier subscribed with LISTEN
[GoodJob] Notifier unsubscribed with UNLISTEN
[GoodJob] Notifier errored: ArgumentError: wrong number of arguments (given 1, expected 0)
["/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/app/models/concerns/good_job/lockable.rb:76:in `block (2 levels) in <module:Lockable>'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `instance_exec'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `block in _exec_scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:804:in `_scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `_exec_scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/scoping/named.rb:176:in `block in scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation/delegation.rb:67:in `block in joins_advisory_locks'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:406:in `block in scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:804:in `_scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:406:in `scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation/delegation.rb:67:in `joins_advisory_locks'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/app/models/concerns/good_job/lockable.rb:102:in `block (2 levels) in <module:Lockable>'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `instance_exec'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `block in _exec_scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:804:in `_scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `_exec_scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/scoping/named.rb:176:in `block in scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation/delegation.rb:67:in `block in advisory_unlocked'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:406:in `block in scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:804:in `_scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:406:in `scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation/delegation.rb:67:in `advisory_unlocked'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/app/models/good_job/process.rb:32:in `block in <class:Process>'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `instance_exec'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `block in _exec_scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:804:in `_scoping'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/relation.rb:411:in `_exec_scope'", "/usr/local/bundle/ruby/3.2.0/gems/activerecord-6.1.7.4/lib/active_record/scoping/named.rb:176:in `block in scope'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/app/models/good_job/process.rb:71:in `cleanup'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/lib/good_job/notifier/process_heartbeat.rb:18:in `block in register_process'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/lib/good_job/assignable_connection.rb:33:in `with_connection'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/lib/good_job/notifier/process_heartbeat.rb:17:in `register_process'", "/usr/local/bundle/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/callbacks.rb:427:in `block in make_lambda'", "/usr/local/bundle/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/callbacks.rb:270:in `block in simple'", "/usr/local/bundle/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/callbacks.rb:516:in `block in invoke_after'", "/usr/local/bundle/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/callbacks.rb:516:in `each'", "/usr/local/bundle/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/callbacks.rb:516:in `invoke_after'", "/usr/local/bundle/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/callbacks.rb:107:in `run_callbacks'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/lib/good_job/notifier.rb:181:in `block (3 levels) in listen'", "/usr/local/bundle/ruby/3.2.0/gems/activesupport-6.1.7.4/lib/active_support/execution_wrapper.rb:91:in `wrap'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/lib/good_job/notifier.rb:180:in `block (2 levels) in listen'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/lib/good_job/notifier.rb:235:in `with_connection'", "/usr/local/bundle/ruby/3.2.0/gems/good_job-3.16.3/lib/good_job/notifier.rb:178:in `block in listen'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:in `block in ns_post_task'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'", "/usr/local/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'"]
```

**Comment by bensheldon** [comment]
@henrylawson sorry about the error! It looks like you're running Rails 6.1 and Ruby 3.2 which aren't compatible, irrespective of GoodJob. There's some details in this issue: https://github.com/bensheldon/good_job/issues/785 . 

Unfortunately, it doesn't look like Rails is planning to cut a formal release with the fixes: https://github.com/rails/rails/pull/46895

**Comment by henrylawson** [comment]
Oh, thanks. I somehow missed that earlier issue. Sorry for the duplicate.

I didn't realize I'd upgraded Ruby beyond what Rails supported, oops!

I've upgraded Rails to 7.0.6 and that has resolved this GoodJob issue for me. FWIW, I've left Ruby at 3.2.2
