### ISSUE TITLE
Daemon and App not connecting to secondary database

### ISSUE THREAD

**Issue by interhive** [bensheldon/good_job#1254]
Rails: **Rails 7.1.3**
GoodJob: **GoodJob: 3.24.0**
Demo Repo: **[https://github.com/interhive/good-job-issues](https://github.com/interhive/good-job-issues)**

I tried to integrate GoodJob into an existing app using a separate database, but I received errors upon startup. The errors indicated that GoodJob could not find the secondary database tables.

I created a brand new Rails app and integrated GoodJob into it using the instructions on the project's README, and I encountered the same errors:

```shell
❯ overmind s
system | Tmux socket name: overmind-good-job-issues-gD4Owvy1b6tVfZSsUppqO
system | Tmux session ID: good-job-issues
system | Listening at ./.overmind.sock
worker | Started with pid 15603...
worker | [GoodJob] [15605] GoodJob 3.24.0 started scheduler with queues=* max_threads=5.
worker | [GoodJob] Notifier errored: NoMethodError: undefined method `each' for :secondary:Symbol
worker |  ["/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_handling.rb:97:in `block in connects_to'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_handling.rb:96:in `each'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_handling.rb:96:in `connects_to'", "/Users/cgrant/code/c2c/good_job_issues/config/initializers/good_job.rb:2:in `block in <main>'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/engine.rb:46:in `class_eval'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/engine.rb:46:in `block (3 levels) in <class:Engine>'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/lazy_load_hooks.rb:77:in `each'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/app/models/good_job/base_record.rb:43:in `<class:BaseRecord>'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/app/models/good_job/base_record.rb:8:in `<module:GoodJob>'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/app/models/good_job/base_record.rb:3:in `<main>'", "<internal:/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "<internal:/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/app/models/good_job/base_execution.rb:6:in `<module:GoodJob>'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/app/models/good_job/base_execution.rb:3:in `<main>'", "<internal:/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "<internal:/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/app/models/good_job/execution.rb:5:in `<module:GoodJob>'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/app/models/good_job/execution.rb:3:in `<main>'", "<internal:/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "<internal:/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/notifier.rb:251:in `block in with_connection'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/execution_wrapper.rb:92:in `wrap'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/notifier.rb:250:in `with_connection'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/notifier.rb:198:in `block in create_listen_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:in `block in ns_post_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'"]
worker | [GoodJob] Notifier subscribed with LISTEN
worker | [GoodJob] GoodJob error: ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "good_jobs" does not exist
worker | LINE 10:  WHERE a.attrelid = '"good_jobs"'::regclass
worker |                              ^
worker |
worker |  ["/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/notifications/instrumenter.rb:58:in `instrument'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:1074:in `column_definitions'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:109:in `columns'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:346:in `block in columns'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:345:in `fetch'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:345:in `columns'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:354:in `block in columns_hash'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:353:in `fetch'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:353:in `columns_hash'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:58:in `columns_hash'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/schema_cache.rb:188:in `columns_hash'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/model_schema.rb:618:in `load_schema!'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/attributes.rb:264:in `load_schema!'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/model_schema.rb:563:in `block in load_schema'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/model_schema.rb:560:in `synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/model_schema.rb:560:in `load_schema'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/model_schema.rb:425:in `columns_hash'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/inheritance.rb:88:in `descends_from_active_record?'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/inheritance.rb:94:in `finder_needs_type_condition?'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/core.rb:407:in `relation'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/scoping/named.rb:45:in `default_scoped'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/scoping/named.rb:32:in `all'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/scoping/named.rb:175:in `block in scope'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/job_performer.rb:108:in `job_query'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/job_performer.rb:33:in `next'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/scheduler.rb:272:in `block (2 levels) in create_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/reloader.rb:77:in `block in wrap'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/execution_wrapper.rb:92:in `wrap'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3/lib/active_support/reloader.rb:74:in `wrap'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/good_job-3.24.0/lib/good_job/scheduler.rb:271:in `block in create_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:in `block in ns_post_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'", "/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'"]

...
```

### Database Configuration:
```yaml
development:
  primary:
    <<: *default
    database: good_job_issues_development
  secondary:
    <<: *default
    database: secondary_development
    migrations_paths: db/goodjob_migrate
```

### secondary_schema.rb
```ruby
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.1].define(version: 2024_02_19_152518) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "good_job_batches", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.text "description"
    t.jsonb "serialized_properties"
    t.text "on_finish"
    t.text "on_success"
    t.text "on_discard"
    t.text "callback_queue_name"
    t.integer "callback_priority"
    t.datetime "enqueued_at"
    t.datetime "discarded_at"
    t.datetime "finished_at"
  end

  create_table "good_job_executions", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.uuid "active_job_id", null: false
    t.text "job_class"
    t.text "queue_name"
    t.jsonb "serialized_params"
    t.datetime "scheduled_at"
    t.datetime "finished_at"
    t.text "error"
    t.integer "error_event", limit: 2
    t.index ["active_job_id", "created_at"], name: "index_good_job_executions_on_active_job_id_and_created_at"
  end

  create_table "good_job_processes", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.jsonb "state"
  end

  create_table "good_job_settings", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.text "key"
    t.jsonb "value"
    t.index ["key"], name: "index_good_job_settings_on_key", unique: true
  end

  create_table "good_jobs", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.text "queue_name"
    t.integer "priority"
    t.jsonb "serialized_params"
    t.datetime "scheduled_at"
    t.datetime "performed_at"
    t.datetime "finished_at"
    t.text "error"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.uuid "active_job_id"
    t.text "concurrency_key"
    t.text "cron_key"
    t.uuid "retried_good_job_id"
    t.datetime "cron_at"
    t.uuid "batch_id"
    t.uuid "batch_callback_id"
    t.boolean "is_discrete"
    t.integer "executions_count"
    t.text "job_class"
    t.integer "error_event", limit: 2
    t.text "labels", array: true
    t.index ["active_job_id", "created_at"], name: "index_good_jobs_on_active_job_id_and_created_at"
    t.index ["batch_callback_id"], name: "index_good_jobs_on_batch_callback_id", where: "(batch_callback_id IS NOT NULL)"
    t.index ["batch_id"], name: "index_good_jobs_on_batch_id", where: "(batch_id IS NOT NULL)"
    t.index ["concurrency_key"], name: "index_good_jobs_on_concurrency_key_when_unfinished", where: "(finished_at IS NULL)"
    t.index ["cron_key", "created_at"], name: "index_good_jobs_on_cron_key_and_created_at_cond", where: "(cron_key IS NOT NULL)"
    t.index ["cron_key", "cron_at"], name: "index_good_jobs_on_cron_key_and_cron_at_cond", unique: true, where: "(cron_key IS NOT NULL)"
    t.index ["finished_at"], name: "index_good_jobs_jobs_on_finished_at", where: "((retried_good_job_id IS NULL) AND (finished_at IS NOT NULL))"
    t.index ["labels"], name: "index_good_jobs_on_labels", where: "(labels IS NOT NULL)", using: :gin
    t.index ["priority", "created_at"], name: "index_good_job_jobs_for_candidate_lookup", where: "(finished_at IS NULL)"
    t.index ["priority", "created_at"], name: "index_good_jobs_jobs_on_priority_created_at_when_unfinished", order: { priority: "DESC NULLS LAST" }, where: "(finished_at IS NULL)"
    t.index ["queue_name", "scheduled_at"], name: "index_good_jobs_on_queue_name_and_scheduled_at", where: "(finished_at IS NULL)"
    t.index ["scheduled_at"], name: "index_good_jobs_on_scheduled_at", where: "(finished_at IS NULL)"
  end

end
```

### good_job.rb Initializer
```ruby
GoodJob.configure_active_record do
  connects_to database: :secondary
end

GoodJob.active_record_parent_class = "ApplicationRecord"
```

### Procfile
```shell
worker: bundle exec good_job start
```

**Comment by bensheldon** [comment]
Briefly, this might be the problem: you can't use both of these configurations: 

```
GoodJob.configure_active_record do
  connects_to database: :secondary
end

GoodJob.active_record_parent_class = "ApplicationRecord"
```

You probably just want the first one (configure_active_record) because you want to use that custom database connection, whereas I imagine your ApplicationRecord is configured to use the not-GoodJob database.

**Comment by bensheldon** [comment]
> probably goes to show that most people (myself included) don't use a separate database for GoodJob.

lol, I' wrong: I started setting that up last week for a project that started using pgbouncer and I needed a direct connection to Postgres. Guess I should test it more before deploying 😬

**Comment by interhive** [comment]
> Looking at that Active Record error in your logs, I think the GoodJob docs are just wrong on how to use multiple databases (the `database:` kwarg requires a hash with { ROLE: NAME }):
> 
> ```
> worker | [GoodJob] Notifier errored: NoMethodError: undefined method `each' for :secondary:Symbol
> worker |  ["/Users/cgrant/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3/lib/active_record/connection_handling.rb:97:in `block in connects_to'"
> ```
> 
> https://github.com/rails/rails/blob/36c1591bcb5e0ee3084759c7f42a706fe5bb7ca7/activerecord/lib/active_record/connection_handling.rb#L97
> 
> I think it should be in your case:
> 
> ```
> GoodJob.configure_active_record do
>   connects_to database: { writing: :secondary }
> end
> ```
> 
> And those docs should be fixed; probably goes to show that most people (myself included) don't use a separate database for GoodJob.

This appears to have fixed the issue. I need to do some more testing, but at least the connection error went away!

Thanks for your help! We look forward to testing and (hopefully) switching over from Sidekiq. The batch capability makes it all worth it.
