### ISSUE TITLE
Edge rails changes breaking binding commits

### ISSUE THREAD

**Issue by robinator** [bensheldon/good_job#1466]
A recent change in edge rails is causing a bunch of queries to fail.  I traced the offending change to an area of code where the [binds arguments are being ignored unless `prepare: true`.](https://github.com/rails/rails/pull/52428/files#r1713956174)  I think this may be a regression in rails but I'm posting here as well in case anyone else is getting this error.

Offending change in rails:
https://github.com/rails/rails/pull/52428

```log
ActionView::Template::Error (PG::UndefinedParameter: ERROR:  there is no parameter $1
LINE 1: SELECT * FROM generate_series( date_trunc('hour', $1::timest...
                                                          ^
)
Caused by: ActiveRecord::StatementInvalid (PG::UndefinedParameter: ERROR:  there is no parameter $1
LINE 1: SELECT * FROM generate_series( date_trunc('hour', $1::timest...
                                                          ^
)
Caused by: PG::UndefinedParameter (ERROR:  there is no parameter $1
LINE 1: SELECT * FROM generate_series( date_trunc('hour', $1::timest...
                                                          ^
)

Information for: ActionView::Template::Error (PG::UndefinedParameter: ERROR:  there is no parameter $1
LINE 1: SELECT * FROM generate_series( date_trunc('hour', $1::timest...
                                                          ^
):
    1: <%= render 'good_job/shared/filter', title: t("good_job.shared.navbar.jobs"), filter: @filter %>
    2: <%= render 'good_job/shared/chart', chart_data: GoodJob::ScheduledByQueueChart.new(@filter).data %>
    3: 
    4: <div data-live-poll-region="jobs-table">
    5:   <%= render 'good_job/jobs/table', jobs: @filter.records, filter: @filter %>
  

Information for cause: ActiveRecord::StatementInvalid (PG::UndefinedParameter: ERROR:  there is no parameter $1
LINE 1: SELECT * FROM generate_series( date_trunc('hour', $1::timest...
                                                          ^
):
  

Information for cause: PG::UndefinedParameter (ERROR:  there is no parameter $1
LINE 1: SELECT * FROM generate_series( date_trunc('hour', $1::timest...
                                                          ^
):
  
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `perform_query'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:556:in `block (2 levels) in raw_execute'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1004:in `block in with_raw_connection'
rails (d7f93473682d) activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:555:in `block in raw_execute'
rails (d7f93473682d) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1122:in `log'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:554:in `raw_execute'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:591:in `internal_execute'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:547:in `internal_exec_query'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:148:in `exec_query'
rails (d7f93473682d) activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:26:in `exec_query'
good_job (a61fc09cdc06) app/charts/good_job/scheduled_by_queue_chart.rb:33:in `data'
good_job (a61fc09cdc06) app/views/good_job/jobs/index.html.erb:2
rails (d7f93473682d) actionview/lib/action_view/base.rb:281:in `public_send'
rails (d7f93473682d) actionview/lib/action_view/base.rb:281:in `_run'
rails (d7f93473682d) actionview/lib/action_view/template.rb:275:in `block in render'
rails (d7f93473682d) activesupport/lib/active_support/notifications.rb:212:in `instrument'
rails (d7f93473682d) actionview/lib/action_view/template.rb:574:in `instrument_render_template'
rails (d7f93473682d) actionview/lib/action_view/template.rb:263:in `render'
rails (d7f93473682d) actionview/lib/action_view/renderer/template_renderer.rb:66:in `block (2 levels) in render_template'
rails (d7f93473682d) activesupport/lib/active_support/notifications.rb:210:in `block in instrument'
rails (d7f93473682d) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (d7f93473682d) activesupport/lib/active_support/notifications.rb:210:in `instrument'
rails (d7f93473682d) actionview/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
rails (d7f93473682d) actionview/lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
rails (d7f93473682d) activesupport/lib/active_support/notifications.rb:210:in `block in instrument'
rails (d7f93473682d) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (d7f93473682d) activesupport/lib/active_support/notifications.rb:210:in `instrument'
rails (d7f93473682d) actionview/lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
rails (d7f93473682d) actionview/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
rails (d7f93473682d) actionview/lib/action_view/renderer/template_renderer.rb:11:in `render'
rails (d7f93473682d) actionview/lib/action_view/renderer/renderer.rb:58:in `render_template_to_object'
rails (d7f93473682d) actionview/lib/action_view/renderer/renderer.rb:31:in `render_to_object'
rails (d7f93473682d) actionview/lib/action_view/rendering.rb:135:in `block in _render_template'
rails (d7f93473682d) actionview/lib/action_view/base.rb:308:in `in_rendering_context'
rails (d7f93473682d) actionview/lib/action_view/rendering.rb:134:in `_render_template'
rails (d7f93473682d) actionpack/lib/action_controller/metal/streaming.rb:179:in `_render_template'
rails (d7f93473682d) actionview/lib/action_view/rendering.rb:121:in `render_to_body'
rails (d7f93473682d) actionpack/lib/action_controller/metal/rendering.rb:186:in `render_to_body'
rails (d7f93473682d) actionpack/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
rails (d7f93473682d) actionpack/lib/abstract_controller/rendering.rb:29:in `render'
rails (d7f93473682d) actionpack/lib/action_controller/metal/rendering.rb:167:in `render'
rails (d7f93473682d) actionpack/lib/action_controller/metal/instrumentation.rb:32:in `block (2 levels) in render'
/Users/rob/.rbenv/versions/3.3.4/lib/ruby/3.3.0/benchmark.rb:313:in `realtime'
rails (d7f93473682d) activesupport/lib/active_support/core_ext/benchmark.rb:14:in `ms'
rails (d7f93473682d) actionpack/lib/action_controller/metal/instrumentation.rb:32:in `block in render'
rails (d7f93473682d) actionpack/lib/action_controller/metal/instrumentation.rb:101:in `cleanup_view_runtime'
rails (d7f93473682d) activerecord/lib/active_record/railties/controller_runtime.rb:46:in `cleanup_view_runtime'
rails (d7f93473682d) actionpack/lib/action_controller/metal/instrumentation.rb:31:in `render'
rails (d7f93473682d) actionpack/lib/action_controller/metal/implicit_render.rb:39:in `default_render'
rails (d7f93473682d) actionpack/lib/action_controller/metal/basic_implicit_render.rb:9:in `send_action'
rails (d7f93473682d) actionpack/lib/abstract_controller/base.rb:226:in `process_action'
rails (d7f93473682d) actionpack/lib/action_controller/metal/rendering.rb:193:in `process_action'
rails (d7f93473682d) actionpack/lib/abstract_controller/callbacks.rb:261:in `block in process_action'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
i18n (1.14.5) lib/i18n.rb:351:in `with_locale'
good_job (a61fc09cdc06) app/controllers/good_job/application_controller.rb:37:in `use_good_job_locale'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
turbo-rails (2.0.6) lib/turbo-rails.rb:24:in `with_request_id'
turbo-rails (2.0.6) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
ahoy_matey (5.1.0) lib/ahoy/controller.rb:50:in `set_ahoy_request_store'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
rails (d7f93473682d) actiontext/lib/action_text/rendering.rb:25:in `with_renderer'
rails (d7f93473682d) actiontext/lib/action_text/engine.rb:71:in `block (4 levels) in <class:Engine>'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:130:in `instance_exec'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:141:in `run_callbacks'
rails (d7f93473682d) actionpack/lib/abstract_controller/callbacks.rb:260:in `process_action'
rails (d7f93473682d) actionpack/lib/action_controller/metal/rescue.rb:27:in `process_action'
rails (d7f93473682d) actionpack/lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
rails (d7f93473682d) activesupport/lib/active_support/notifications.rb:210:in `block in instrument'
rails (d7f93473682d) activesupport/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails (d7f93473682d) activesupport/lib/active_support/notifications.rb:210:in `instrument'
rails (d7f93473682d) actionpack/lib/action_controller/metal/instrumentation.rb:76:in `process_action'
rails (d7f93473682d) actionpack/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
rails (d7f93473682d) activerecord/lib/active_record/railties/controller_runtime.rb:39:in `process_action'
rails (d7f93473682d) actionpack/lib/abstract_controller/base.rb:163:in `process'
rails (d7f93473682d) actionview/lib/action_view/rendering.rb:40:in `process'
rails (d7f93473682d) actionpack/lib/action_controller/metal.rb:252:in `dispatch'
rails (d7f93473682d) actionpack/lib/action_controller/metal.rb:335:in `dispatch'
rails (d7f93473682d) actionpack/lib/action_dispatch/routing/route_set.rb:67:in `dispatch'
rails (d7f93473682d) actionpack/lib/action_dispatch/routing/route_set.rb:50:in `serve'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:53:in `block in serve'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:126:in `each'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:126:in `find_routes'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:34:in `serve'
rails (d7f93473682d) actionpack/lib/action_dispatch/routing/route_set.rb:908:in `call'
rails (d7f93473682d) railties/lib/rails/engine/lazy_route_set.rb:68:in `call'
rails (d7f93473682d) railties/lib/rails/engine.rb:537:in `call'
rails (d7f93473682d) railties/lib/rails/railtie.rb:226:in `public_send'
rails (d7f93473682d) railties/lib/rails/railtie.rb:226:in `method_missing'
rails (d7f93473682d) actionpack/lib/action_dispatch/routing/mapper.rb:33:in `block in <class:Constraints>'
rails (d7f93473682d) actionpack/lib/action_dispatch/routing/mapper.rb:62:in `serve'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:53:in `block in serve'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:126:in `each'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:126:in `find_routes'
rails (d7f93473682d) actionpack/lib/action_dispatch/journey/router.rb:34:in `serve'
rails (d7f93473682d) actionpack/lib/action_dispatch/routing/route_set.rb:908:in `call'
rails (d7f93473682d) railties/lib/rails/engine/lazy_route_set.rb:68:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/static.rb:27:in `call'
omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.2) lib/omniauth/builder.rb:44:in `call'
rack (3.1.7) lib/rack/static.rb:161:in `call'
rack (3.1.7) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.1.7) lib/rack/etag.rb:29:in `call'
rack (3.1.7) lib/rack/conditional_get.rb:31:in `call'
rack (3.1.7) lib/rack/head.rb:15:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/cookies.rb:704:in `call'
rails (d7f93473682d) activerecord/lib/active_record/migration.rb:674:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
rails (d7f93473682d) activesupport/lib/active_support/callbacks.rb:101:in `run_callbacks'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/callbacks.rb:30:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
rails (d7f93473682d) railties/lib/rails/rack/logger.rb:41:in `call_app'
rails (d7f93473682d) railties/lib/rails/rack/logger.rb:29:in `call'
ahoy_matey (5.1.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
request_store (1.7.0) lib/request_store/middleware.rb:19:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/request_id.rb:33:in `call'
rack (3.1.7) lib/rack/method_override.rb:28:in `call'
rack (3.1.7) lib/rack/runtime.rb:24:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/static.rb:27:in `call'
rack (3.1.7) lib/rack/sendfile.rb:114:in `call'
rails (d7f93473682d) actionpack/lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
rails (d7f93473682d) railties/lib/rails/engine.rb:537:in `call'
puma (6.4.2) lib/puma/configuration.rb:272:in `call'
puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
puma (6.4.2) lib/puma/server.rb:464:in `process_client'
puma (6.4.2) lib/puma/server.rb:245:in `block in run'
puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by bensheldon** [comment]
Thank you so much for reporting this! ❤
