### ISSUE TITLE
bin/rails g good_job:install fails

### ISSUE THREAD

**Issue by lain0** [bensheldon/good_job#1481]
```ruby
ruby:
  - ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-darwin23]

rails: Rails 7.2.1
```

```ruby
rails new rails7 --minimal -T
bundle add good_job
bin/rails g good_job:install

.rvm/gems/ruby-3.3.3/gems/good_job-4.2.1/lib/good_job/configuration.rb:21:in `<class:Configuration>': undefined method `days' for an instance of Integer (NoMethodError)

    DEFAULT_CLEANUP_PRESERVED_JOBS_BEFORE_SECONDS_AGO = 14.days.to_i
                                                          ^^^^^
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/good_job-4.2.1/lib/good_job/configuration.rb:9:in `<module:GoodJob>'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/good_job-4.2.1/lib/good_job/configuration.rb:3:in `<top (required)>'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/good_job-4.2.1/lib/good_job.rb:26:in `require_relative'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/good_job-4.2.1/lib/good_job.rb:26:in `<top (required)>'
	from <internal:/Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundler.rb:207:in `require'
	from /Users/serj/code/m10/rails7/config/application.rb:19:in `<top (required)>'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/command/actions.rb:15:in `require_application!'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/command/actions.rb:19:in `boot_application!'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/command/base.rb:73:in `perform'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/command.rb:71:in `block in invoke'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/command.rb:149:in `with_argv'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/command.rb:69:in `invoke'
	from /Users/serj/.rvm/gems/ruby-3.3.3/gems/railties-7.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/serj/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from bin/rails:4:in `<main>'
	```

**Comment by lain0** [comment]
sorry with minimal rails boesn't require  require "active_job/railtie" by default so i'm sop nooby*)
