### ISSUE TITLE
Bug: calling GoodJob.restart in Puma on_worker_boot still starts GoodJob regardless of it being in async mode or not

### ISSUE THREAD

**Issue by amanfredi** [bensheldon/good_job#1531]
Thanks for the great work on GoodJob! 

This issue was originally reported in https://github.com/bensheldon/good_job/issues/1054 and reported fixed in https://github.com/bensheldon/good_job/pull/1055.

This fix doesn't seem to work properly. In puma on_worker_boot my caller stack looks like this:

```["/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:320:in `block in run_hooks'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:314:in `each'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:314:in `run_hooks'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster/worker.rb:57:in `run'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster.rb:216:in `worker'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster.rb:97:in `block in spawn_worker'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster.rb:97:in `fork'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster.rb:97:in `spawn_worker'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster.rb:81:in `block in spawn_workers'", "<internal:numeric>:237:in `times'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster.rb:74:in `spawn_workers'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cluster.rb:430:in `run'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/launcher.rb:194:in `run'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cli.rb:75:in `run'", "/opt/gems/ruby/3.3.0/gems/puma-6.4.3/bin/puma:10:in `<top (required)>'", "/opt/gems/ruby/3.3.0/bin/puma:25:in `load'", "/opt/gems/ruby/3.3.0/bin/puma:25:in `<main>'"]```

This doesn't trigger the grep filter for 'puma/request' checked by `GoodJob.configuration.in_webserver?` and thus a capsule is still started for each puma worker when GoodJob.restart is called.

**Comment by bensheldon** [comment]
Thanks for opening the issue! There should probably be a line for `puma/launcher` or puma/cluster` in `GoodJob.configuration.in_webserver?` too. Would you be able to make a PR for that?

**Comment by amanfredi** [comment]
Yes, I can put together a PR
