### ISSUE TITLE
ActiveJob concurrency raises FrozenError

### ISSUE THREAD

**Issue by christianrolle** [bensheldon/good_job#386]
After I included `GoodJob::ActiveJobExtensions::Concurrency` into my recurring job:

```
class SynchronizeMediaJob < ApplicationJob
  include GoodJob::ActiveJobExtensions::Concurrency

  good_job_control_concurrency_with(
    # Maximum number of unfinished jobs to allow with the concurrency key
    total_limit: 1,
    key: -> { 'SynchronizeMediaJob' }
  )

  def perform
    Medium.unpushed.find_each |medium|
      medium.push!
    end
  end
end
```
all my specs are failing due to:

```
An error occurred while loading ./spec/requests/visits/update_spec.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

FrozenError:
  can't modify frozen #<Class:#<Array:0x00005559009bde90>>: ["/usr/src/app/app/channels", "/usr/src/app/app/controllers", "/usr/src/app/app/controllers/concerns", "/usr/src/app/app/datatables", "/usr/src/app/app/decorators", "/usr/src/app/app/forms", "/usr/src/app/app/helpers", "/usr/src/app/app/interactors", "/usr/src/app/app/jobs", "/usr/src/app/app/mailers", "/usr/src/app/app/models", "/usr/src/app/app/models/concerns", "/usr/src/app/app/policies", "/usr/src/app/app/representers", "/usr/src/app/app/services", #<Pathname:/usr/src/app/lib>, "/bundle/ruby/2.7.0/gems/devise-4.7.3/app/controllers", "/bundle/ruby/2.7.0/gems/devise-4.7.3/app/helpers", "/bundle/ruby/2.7.0/gems/devise-4.7.3/app/mailers", "/bundle/ruby/2.7.0/gems/actiontext-6.1.0/app/helpers", "/bundle/ruby/2.7.0/gems/actiontext-6.1.0/app/models", "/bundle/ruby/2.7.0/gems/actionmailbox-6.1.0/app/controllers", "/bundle/ruby/2.7.0/gems/actionmailbox-6.1.0/app/jobs", "/bundle/ruby/2.7.0/gems/actionmailbox-6.1.0/app/models", "/bundle/ruby/2.7.0/gems/activestorage-6.1.0/app/controllers", "/bundle/ruby/2.7.0/gems/activestorage-6.1.0/app/controllers/concerns", "/bundle/ruby/2.7.0/gems/activestorage-6.1.0/app/jobs", "/bundle/ruby/2.7.0/gems/activestorage-6.1.0/app/models"]
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/change_observer.rb:21:in `unshift'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/change_observer.rb:21:in `unshift'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/engine.rb:588:in `block in <class:Engine>'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/initializable.rb:32:in `instance_exec'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/initializable.rb:32:in `run'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/initializable.rb:61:in `block in run_initializers'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/initializable.rb:50:in `each'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/initializable.rb:50:in `tsort_each_child'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/initializable.rb:60:in `run_initializers'
# /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/application.rb:384:in `initialize!'
# ./config/environment.rb:5:in `<top (required)>'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
# /bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
# /bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
# ./spec/requests/visits/update_spec.rb:1:in `<top (required)>'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
# /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
```

My GoodJob configuration:

```
# config/environments/production.rb

require "active_support/core_ext/integer/time"
require Rails.root.join 'app/services/smtp_password_service.rb'

Rails.application.configure do
  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true
  config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.compile = false
  config.active_storage.service = :amazon
  config.log_level = :info
  config.log_tags = [:request_id]
  config.action_mailer.perform_caching = false
  config.action_mailer.deliver_later_queue_name = 'default'
  config.action_mailer.default_options = {
    charset: 'UTF-8'
  }
  config.action_mailer.perform_deliveries = true
  config.action_mailer.smtp_settings = {
    address: ENV['SMTP_HOST'],
    port: 587,
    user_name: ENV['AWS_ACCESS_KEY_ID'],
    password: SmtpPasswordService.build(secret: ENV['AWS_SECRET_ACCESS_KEY'],
                                        region: ENV['AWS_REGION']),
    authentication: 'plain',
    enable_starttls_auto: true
  }
  config.i18n.fallbacks = true
  config.active_support.deprecation = :notify
  config.active_support.disallowed_deprecation = :log
  config.active_support.disallowed_deprecation_warnings = []
  config.log_formatter = ::Logger::Formatter.new
  config.active_record.dump_schema_after_migration = false

  config.good_job.enable_cron = true

  config.good_job.cron = {
    # Every minute
    synchronize_media: {
      cron: '* * * * *',
      class: 'SynchronizeMediaJob',
      set: { priority: -1 },
      description: 'Synchronizes visit media with Gateway'
    }
  }
end
```
and
```
class ApplicationJob < ActiveJob::Base
  class GatewayConnectException < StandardError; end
  retry_on GatewayConnectException, wait: :exponentially_longer, attempts: 5
end
```

As soon as I comment out the ActiveJobExtensions::Concurrency related, the specs are running.
Any idea?

**Comment by bensheldon** [comment]
@christianrolle I haven't seen that error before and I'm happy to help figure out what's happening. From looking at StackOverflow, the frozen array error might not be the root cause: https://stackoverflow.com/a/50371654/241735

Could you please try targeting a single spec (e.g. `bundle exec rspec spec/requests/visits/update_spec.rb`) and share the complete output. Also, could you share what is in your `config/environments/test.rb` file?
