### ISSUE TITLE
Can't cast Array

### ISSUE THREAD

**Issue by JonathanFrias** [bensheldon/good_job#529]
I'm seeing this error when loading the dashboard in rails 7

```
Started GET "/jobs" for ::1 at 2022-02-21 22:53:42 -0500
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
Processing by GoodJob::ExecutionsController#index as HTML
  Rendering layout /Users/jonathan/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/good_job-2.7.1/engine/app/views/layouts/good_job/base.html.erb
  Rendering /Users/jonathan/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/good_job-2.7.1/engine/app/views/good_job/executions/index.html.erb within layouts/good_job/base
  Rendered /Users/jonathan/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/good_job-2.7.1/engine/app/views/good_job/executions/index.html.erb within layouts/good_job/base (Duration: 1.4ms | Allocations: 1302)
  Rendered layout /Users/jonathan/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/good_job-2.7.1/engine/app/views/layouts/good_job/base.html.erb (Duration: 1.5ms | Allocations: 1373)
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms | Allocations: 1816)



ActionView::Template::Error (can't cast Array):
    1: <div class="card my-3 p-6">
    2:   <%= render 'good_job/shared/chart', chart_data: GoodJob::ScheduledByQueueChart.new(@filter).data %>
    3: </div>
    4:
    5: <%= render 'good_job/shared/filter', filter: @filter %>

activerecord (7.0.2) lib/active_record/connection_adapters/abstract/quoting.rb:43:in `type_cast'
activerecord (7.0.2) lib/active_record/connection_adapters/postgresql/quoting.rb:116:in `type_cast'
activerecord (7.0.2) lib/active_record/connection_adapters/abstract/quoting.rb:211:in `block in type_casted_binds'
activerecord (7.0.2) lib/active_record/connection_adapters/abstract/quoting.rb:207:in `map'
activerecord (7.0.2) lib/active_record/connection_adapters/abstract/quoting.rb:207:in `type_casted_binds'
activerecord (7.0.2) lib/active_record/connection_adapters/postgresql_adapter.rb:765:in `exec_no_cache'
activerecord (7.0.2) lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
activerecord (7.0.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
good_job (2.7.1) engine/app/charts/good_job/scheduled_by_queue_chart.rb:34:in `data'
good_job (2.7.1) engine/app/views/good_job/executions/index.html.erb:2
actionview (7.0.2) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.2) lib/action_view/base.rb:244:in `_run'
actionview (7.0.2) lib/action_view/template.rb:157:in `block in render'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.2) lib/action_view/template.rb:361:in `instrument_render_template'
actionview (7.0.2) lib/action_view/template.rb:155:in `render'
actionview (7.0.2) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.2) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
actionview (7.0.2) lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.2) lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
actionview (7.0.2) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
actionview (7.0.2) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (7.0.2) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (7.0.2) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.0.2) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (7.0.2) lib/action_view/base.rb:270:in `in_rendering_context'
actionview (7.0.2) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (7.0.2) lib/action_controller/metal/streaming.rb:216:in `_render_template'
actionview (7.0.2) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (7.0.2) lib/action_controller/metal/rendering.rb:46:in `render_to_body'
actionpack (7.0.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (7.0.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (7.0.2) lib/action_controller/metal/rendering.rb:30:in `render'
actionpack (7.0.2) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
benchmark (0.1.0) lib/benchmark.rb:308:in `realtime'
activesupport (7.0.2) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (7.0.2) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
actionpack (7.0.2) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
activerecord (7.0.2) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (7.0.2) lib/action_controller/metal/instrumentation.rb:21:in `render'
actionpack (7.0.2) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (7.0.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
<internal:kernel>:90:in `tap'
actionpack (7.0.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.0.2) lib/abstract_controller/base.rb:214:in `process_action'
actionpack (7.0.2) lib/action_controller/metal/rendering.rb:53:in `process_action'
actionpack (7.0.2) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
i18n (1.9.1) lib/i18n.rb:328:in `with_locale'
good_job (2.7.1) engine/app/controllers/good_job/base_controller.rb:30:in `switch_locale'
activesupport (7.0.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
actiontext (7.0.2) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.2) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.2) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.2) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.2) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.2) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.2) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.2) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.2) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.2) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.2) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.2) lib/action_dispatch/routing/route_set.rb:850:in `call'
railties (7.0.2) lib/rails/engine.rb:530:in `call'
railties (7.0.2) lib/rails/railtie.rb:224:in `public_send'
railties (7.0.2) lib/rails/railtie.rb:224:in `method_missing'
actionpack (7.0.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.2) lib/action_dispatch/routing/route_set.rb:850:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (7.0.2) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (7.0.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/cookies.rb:693:in `call'
activerecord (7.0.2) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.2) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
rollbar (3.3.0) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
rollbar (3.3.0) lib/rollbar.rb:145:in `scoped'
rollbar (3.3.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
rollbar (3.3.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (7.0.2) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.2) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.2) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.2) lib/rails/engine.rb:530:in `call'
puma (5.5.0) lib/puma/configuration.rb:249:in `call'
puma (5.5.0) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.0) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.0) lib/puma/request.rb:76:in `handle_request'
puma (5.5.0) lib/puma/server.rb:447:in `process_client'
puma (5.5.0) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by bensheldon** [comment]
@JonathanFrias that is really strange. I just tried loading up Rails 7.0.2 and couldn't easily reproduce it.

Could you try running this in a Rails console?

```ruby
ActiveRecord::Relation::QueryAttribute.new('start_time', Time.current, ActiveRecord::Type::DateTime.new)
```

...which is the equivalent to what I think is happening on the line that is blowing up in your stacktrace:

https://github.com/bensheldon/good_job/blob/b921729800b1c9a60e25d4cf2a9d53f04e57b951/engine/app/charts/good_job/scheduled_by_queue_chart.rb#L34

**Comment by nbkkb7x** [comment]
Good Morning Ben,

Working on the same codebase as @JonathanFrias and getting the same error as above. Here's the output from that command in Rails Console (On Rails 7.0.2):

`[1] pry(main)> ActiveRecord::Relation::QueryAttribute.new('start_time', Time.current, ActiveRecord::Type::DateTime.new)
=> #<ActiveRecord::Relation::QueryAttribute:0x000055e215a60610
 @name="start_time",
 @original_attribute=nil,
 @type=#<ActiveRecord::Type::DateTime:0x000055e215a60688 @limit=nil, @precision=nil, @scale=nil>,
 @value_before_type_cast=Tue, 22 Feb 2022 13:31:20.446178100 UTC +00:00>`
 
 Hope this can shed a little more light on the issue. Thanks for all your help.

**Comment by bensheldon** [comment]
Oops, I failed to look at the GoodJob version you're running. GoodJob isn't compatible with Rails 7 until GoodJob `v2.7.2` (but you may as well go to the latest, which is `v2.10.0`

I think this is the PR that fixed the problem you're having: #461

**Comment by nbkkb7x** [comment]
That did it. Thanks Ben!

**Comment by bensheldon** [comment]
@JonathanFrias Did updating GoodJob address the problem for you too?
