### ISSUE TITLE
Some dashboard actions have a routing error

### ISSUE THREAD

**Issue by baka-san** [bensheldon/good_job#602]
New to GoodJob. I like it, but I've been having some issues. One thing is with the web interface. I am able to view my jobs just fine, but when I try to use some of the actions (e.g. delete a single job or delete all jobs), I'm getting a routing error. I wonder if it has to do with POST vs PUT, or perhaps it's something unrelated.

<img width="541" alt="Screen Shot 2022-05-20 at 10 45 44" src="https://user-images.githubusercontent.com/15086337/169432394-a622cc00-aa9e-4528-a381-55df0de00dd9.png">

<img width="832" alt="Screen Shot 2022-05-20 at 10 46 25" src="https://user-images.githubusercontent.com/15086337/169432412-fee768f1-cb01-4663-9d51-e2c9917f6bf4.png">

```ruby
Rails.application.routes.draw do
  mount GoodJob::Engine => "good_job"
  ...
end
```

### Environment
Ruby 3.0.2
Rails 6.1.4.1

**Comment by bensheldon** [comment]
@baka-san thanks for opening this issue! We just released the Destroy Job feature a few days ago, so it very much could be a big. I'll take a look.

**Comment by baka-san** [comment]
@bensheldon
Sure thing. It's not a big deal, I just figured it likely was unintended. Thanks for the quick response.

I'm also using API only mode...not sure if that affects anything. I have a separate application_controller, specifically to handle an admin panel and the GoodJob dashboard (did something similar to this http://www.carlosramireziii.com/how-to-add-active-admin-to-a-rails-5-api-application.html).

**Comment by bensheldon** [comment]
@baka-san aha, I think API-only might be the source of the problem. Could you check if adding this solves it?

```rb
# config/application.rb
module MyApp
  class Application < Rails::Application
    # add this =>
    config.middleware.add Rack::MethodOverride
  end
end
```

**Comment by baka-san** [comment]
@bensheldon

I now have the following:
```ruby
# config/application.rb
module MyApp
  class Application < Rails::Application
    # Configure ActiveJob with GoodJob
    config.middleware.use Rack::MethodOverride
    # Needed for API only with the dashboard btw
    config.middleware.use ActionDispatch::Flash
  end
end
```

I'm not sure if it's specific to my application, but I'm now getting this error:

<img width="1010" alt="Screen Shot 2022-05-20 at 12 52 39" src="https://user-images.githubusercontent.com/15086337/169447114-1e70f4f1-d0ad-4d6b-8249-4c2ac2aa7470.png">


```
[actionpack (6.1.4.1) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:199:in `block in halting'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:512:in `block in invoke_before'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:512:in `each'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:512:in `invoke_before'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:115:in `block in run_callbacks'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actiontext (6.1.4.1) lib/action_text/rendering.rb:20:in `with_renderer'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actiontext (6.1.4.1) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `instance_exec'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:137:in `run_callbacks'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `block in instrument'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `instrument'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activerecord (6.1.4.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/abstract_controller/base.rb:165:in `process'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionview (6.1.4.1) lib/action_view/rendering.rb:39:in `process'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal.rb:190:in `dispatch'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_controller/metal.rb:254:in `dispatch'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `each'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:842:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[railties (6.1.4.1) lib/rails/engine.rb:539:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[railties (6.1.4.1) lib/rails/railtie.rb:207:in `public_send'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[railties (6.1.4.1) lib/rails/railtie.rb:207:in `method_missing'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `each'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:842:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[bullet (6.1.5) lib/bullet/rack.rb:15:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[rack (2.2.3) lib/rack/method_override.rb:24:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[rack (2.2.3) lib/rack/etag.rb:27:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[rack (2.2.3) lib/rack/head.rb:12:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activerecord (6.1.4.1) lib/active_record/migration.rb:601:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[railties (6.1.4.1) lib/rails/rack/logger.rb:37:in `call_app'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[railties (6.1.4.1) lib/rails/rack/logger.rb:28:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[rack (2.2.3) lib/rack/runtime.rb:22:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[activesupport (6.1.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/static.rb:24:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[rack (2.2.3) lib/rack/sendfile.rb:110:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[actionpack (6.1.4.1) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[railties (6.1.4.1) lib/rails/engine.rb:539:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[puma (5.5.2) lib/puma/configuration.rb:249:in `call'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[puma (5.5.2) lib/puma/request.rb:76:in `handle_request'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[puma (5.5.2) lib/puma/server.rb:447:in `process_client'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
[puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://127.0.0.1:3000/good_job/jobs/ec63dd8b-42d5-40ae-b3b9-e09e6250bd36?locale=en#)
```

**Comment by bensheldon** [comment]
Sorry, it seems like you'll need to also add too::

```
config.middleware.use ActionDispatch::Cookies
config.middleware.use ActionDispatch::Session::CookieStore
```

**Comment by baka-san** [comment]
@bensheldon 

Ok, that solved this issue. Thanks for the speedy help!

For reference for anyone using API only in the future, I added the following to `config/application.rb`:
```ruby
module MyApp
  class Application < Rails::Application
    config.active_job.queue_adapter = :good_job
    config.middleware.use Rack::MethodOverride
    config.middleware.use ActionDispatch::Flash
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore
  end
end
```
