### ISSUE TITLE
500 Internal Server Error Exception in web interface trying to view running jobs

### ISSUE THREAD

**Issue by rgaufman** [bensheldon/good_job#656]
- [ ] Dashboard should display job details/status without delegation to `job.executions` association, because the two queries introduce a race condition that can 500 the dashboard
- [x] ~~Executions should touch "performed_at" even when `preserve_job_records = false` so running jobs show up in the dashboard.~~ Use lock-state to determine running-ness.
---

Some of my jobs are pretty quick and when switching to the "Running" tab, I just see: "HTTP ERROR 500"

Checking the logs, it shows:

```
2022-07-09 13:15:00.977915 F [1344493:puma srv tp 009 abstract_thread_local_var.rb:43] [a527864a-c1a9-46e3-9913-c797cabfcbc1] Rails -- Exception: ActionView::Template::Error: GoodJob::Job#status delegated to head_execution.status, but head_execution is nil: #<GoodJob::Job id: "54501bf2-f028-4c28-bc85-58a8ae61c952", queue_name: "cloud_copy", priority: 0, serialized_params: {"job_id"=>"7a0f703c-2e9d-487b-8b29-a1fd8ed3d654", "locale"=>"en", "priority"=>nil, "timezone"=>"UTC", "arguments"=>["6290f547a79dfa06e1c45ab1", "video", {"ends_at"=>{"value"=>"2022-07-09T13:10:04.000000000+01:00", "_aj_serialized"=>"ActiveJob::Serializers::TimeSerializer"}, "base_path"=>"/internal/6290f547a79dfa06e1c45ab1/20220709_13/20220709_130901_to_131004.mp4", "starts_at"=>{"value"=>"2022-07-09T13:09:01.000000000+01:00", "_aj_serialized"=>"ActiveJob::Serializers::TimeSerializer"}, "target_path"=>"/data/amex-gbt/ad27131193d0fa71a629/internal/6290f547a79dfa06e1c45ab1/20220709_13/20220709_130901_to_131004.mp4", "_aj_hash_with_indifferent_access"=>true}, 24, "2022-07-09 13:10:15 +0100"], "job_class"=>"CloudCopyJob", "executions"=>0, "queue_name"=>"cloud_copy", "enqueued_at"=>"2022-07-09T12:14:37Z", "provider_job_id"=>nil, "exception_executions"=>{}}, scheduled_at: "2022-07-09 12:15:00.353627000 +0000", performed_at: nil, finished_at: nil, error: nil, created_at: "2022-07-09 12:14:37.354833000 +0000", updated_at: "2022-07-09 12:14:37.354833000 +0000", active_job_id: "7a0f703c-2e9d-487b-8b29-a1fd8ed3d654", concurrency_key: nil, cron_key: nil, retried_good_job_id: nil, cron_at: nil>
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/good_job-3.0.1/lib/models/good_job/job.rb:77:in `rescue in status'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/good_job-3.0.1/lib/models/good_job/job.rb:77:in `status'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/good_job-3.0.1/app/views/good_job/jobs/_table.erb:63:in `block (2 levels) in _vendor_bundle_ruby_______gems_good_job_______app_views_good_job_jobs__table_erb___933794818205606512_354080'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:88:in `each'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/relation/delegation.rb:88:in `each'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/good_job-3.0.1/app/views/good_job/jobs/_table.erb:55:in `block in _vendor_bundle_ruby_______gems_good_job_______app_views_good_job_jobs__table_erb___933794818205606512_354080'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/helpers/capture_helper.rb:45:in `capture'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/helpers/form_helper.rb:768:in `form_with'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/good_job-3.0.1/app/views/good_job/jobs/_table.erb:3:in `_vendor_bundle_ruby_______gems_good_job_______app_views_good_job_jobs__table_erb___933794818205606512_354080'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `public_send'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `_run'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/template.rb:157:in `block in render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/template.rb:361:in `instrument_render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/template.rb:155:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:251:in `block in render_partial_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:237:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:53:in `render_partial'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/helpers/rendering_helper.rb:44:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/good_job-3.0.1/app/views/good_job/jobs/index.html.erb:5:in `_vendor_bundle_ruby_______gems_good_job_______app_views_good_job_jobs_index_html_erb___2658226613160048850_353980'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `public_send'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `_run'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/template.rb:157:in `block in render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/template.rb:361:in `instrument_render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/template.rb:155:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:11:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/rendering.rb:117:in `block in _render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/base.rb:270:in `in_rendering_context'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/rendering.rb:116:in `_render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/streaming.rb:216:in `_render_template'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/rendering.rb:103:in `render_to_body'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:46:in `render_to_body'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/abstract_controller/rendering.rb:25:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:30:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
/usr/local/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:22:in `block in render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:21:in `render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
<internal:kernel>:90:in `tap'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:215:in `process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/good_job-3.0.1/app/controllers/good_job/application_controller.rb:34:in `switch_locale'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:151:in `process'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionview-7.0.3/lib/action_view/rendering.rb:39:in `process'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal.rb:188:in `dispatch'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_controller/metal.rb:251:in `dispatch'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `each'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3/lib/rails/engine.rb:530:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3/lib/rails/railtie.rb:226:in `public_send'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3/lib/rails/railtie.rb:226:in `method_missing'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `each'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:27:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/cookies.rb:697:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/airbrake-13.0.2/lib/airbrake/rack/middleware.rb:34:in `call!'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/airbrake-13.0.2/lib/airbrake/rack/middleware.rb:23:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/data/deployer/timeagent/vendor/cache/rails_semantic_logger-f4c2945e894a/lib/rails_semantic_logger/rack/logger.rb:43:in `call_app'
/data/deployer/timeagent/vendor/cache/rails_semantic_logger-f4c2945e894a/lib/rails_semantic_logger/rack/logger.rb:26:in `block in call'
/data/deployer/timeagent/vendor/cache/semantic_logger-8a1650ac90db/lib/semantic_logger/base.rb:190:in `block in tagged'
/data/deployer/timeagent/vendor/cache/semantic_logger-8a1650ac90db/lib/semantic_logger/semantic_logger.rb:319:in `fast_tag'
/data/deployer/timeagent/vendor/cache/semantic_logger-8a1650ac90db/lib/semantic_logger/semantic_logger.rb:351:in `tagged'
/data/deployer/timeagent/vendor/cache/semantic_logger-8a1650ac90db/lib/semantic_logger/base.rb:202:in `tagged'
/data/deployer/timeagent/vendor/cache/rails_semantic_logger-f4c2945e894a/lib/rails_semantic_logger/rack/logger.rb:26:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/actionpack-7.0.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3/lib/rails/engine.rb:530:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
/data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

Any ideas?

**Comment by bensheldon** [comment]
Thank you for sharing the error backtrace! Particularly `GoodJob::Job#status delegated to head_execution.status, but head_execution is nil`. This is a bug, but it's likely limited because I think most people run with `preserve_job_records = true` whereas I think you have it set to false if this has the same settings as #622.

The query on here is something like `GoodJob::Job.all.include(:executions)`, which results in two queries, and there is a deviation between Jobs, and their relations the Executions (even though both models are reading off the same table). I think I need to rewrite how the Job is displayed so that it needs to delegate less to its `executions` relation.

**Comment by rgaufman** [comment]
Thank you, I enabled preserve_job_records for the time being (I disabled it to investigate the memory leak which is still something I'm trying to figure out! - not sure if it's caused by good_job or not yet, will investigate further soon).

I also noticed that if preserve_job_records is disabled, in the web dashboard the job status never shows :running even in the "running" tab, just a heads up :)

**Comment by bensheldon** [comment]
> I also noticed that if preserve_job_records is disabled, in the web dashboard the job status never shows :running even in the "running" tab, just a heads up :)

Ooh, thanks for flagging that. I think that's the result of an optimization that predates the dashboard. I should update that too. 

https://github.com/bensheldon/good_job/blob/eebf63fd3bb614774c9801c978ebea617ca69f57/lib/models/good_job/execution.rb#L236-L237
