### ISSUE TITLE
Support for Ruby 3.2

### ISSUE THREAD

**Issue by Timmitry** [bensheldon/good_job#785]
Hello and a happy new year!

I just tried to start GoodJob with the newly released Ruby 3.2 for my application, and it raises an error:

```
[GoodJob] Notifier errored: ArgumentError: wrong number of arguments (given 1, expected 0)
```

The error originates from this line:

https://github.com/bensheldon/good_job/blob/f683f3784bfb6e3574c5abeebb4eee15e4a74f20/app/models/good_job/lockable.rb#L75

Not really urgent, but just wanted to share this 🙂

**Comment by Timmitry** [comment]
We are using Rails 6.1.7. Hope that helps to find the issue, if not, I'm glad to provide more information 🙂

**Comment by bensheldon** [comment]
Hmm, this might be an issue with Rails. This looks very similar: https://github.com/rails/rails/issues/46883

**Comment by bensheldon** [comment]
I think this PR will fix it: https://github.com/rails/rails/pull/46895

**Comment by Timmitry** [comment]
Oh, that does indeed look like the problem. So it's not good job but rather the combination of Ruby 3.2 and Rails 6.1 that causes problems. Let's see if they fix it for Rails 6.1, otherwise we will just delay the Ruby update and first do the Rails update 🙂 

Here's the stackrace, even though that should probably not be an issue anymore:

<details>
    <summary>Stacktrace</summary>

```
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/app/models/good_job/lockable.rb:75:in `block (2 levels) in <module:Lockable>'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `instance_exec'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `block in _exec_scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:804:in `_scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `_exec_scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/scoping/named.rb:176:in `block in scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation/delegation.rb:67:in `block in joins_advisory_locks'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:406:in `block in scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:804:in `_scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:406:in `scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation/delegation.rb:67:in `joins_advisory_locks'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/app/models/good_job/lockable.rb:101:in `block (2 levels) in <module:Lockable>'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `instance_exec'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `block in _exec_scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:804:in `_scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `_exec_scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/scoping/named.rb:176:in `block in scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation/delegation.rb:67:in `block in advisory_unlocked'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:406:in `block in scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:804:in `_scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:406:in `scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation/delegation.rb:67:in `advisory_unlocked'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/app/models/good_job/process.rb:26:in `block in <class:Process>'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `instance_exec'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `block in _exec_scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:804:in `_scoping'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:411:in `_exec_scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7/lib/active_record/scoping/named.rb:176:in `block in scope'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/app/models/good_job/process.rb:57:in `cleanup'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/lib/good_job/notifier/process_registration.rb:17:in `block in register_process'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/lib/good_job/assignable_connection.rb:32:in `with_connection'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/lib/good_job/notifier/process_registration.rb:16:in `register_process'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:270:in `block in simple'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `block in invoke_after'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `each'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `invoke_after'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:107:in `run_callbacks'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/lib/good_job/notifier.rb:171:in `block (2 levels) in listen'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/lib/good_job/notifier.rb:215:in `with_connection'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/good_job-3.7.2/lib/good_job/notifier.rb:169:in `block in listen'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/ivar.rb:169:in `safe_execute'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:in `block in ns_post_task'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'"
"/Users/tim.landwerth/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'"
```

</details>

**Comment by morgoth** [comment]
@Timmitry Can this issue be closed, as it's Rails related.
FYI: I'm using GJ on Ruby 3.2 without a problem with latest stable Rails release

**Comment by Timmitry** [comment]
@morgoth Yes, I think so, for people using Rails 6.1, the corresponding issue is linked, and as you said, it works with Ruby 3.2, so all good, thanks 👍
