### ISSUE TITLE
Rails 7.1 - Serialized columns like a store now needs a `coder: JSON`

### ISSUE THREAD

**Issue by mhenrixon** [bensheldon/good_job#863]
```
missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`. (ArgumentError)

            raise ArgumentError, <<~MSG.squish
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  from gems/3.2.0/gems/good_job-3.12.3/app/models/good_job/batch_record.rb:76:in `<class:BatchRecord>'
  from gems/3.2.0/gems/good_job-3.12.3/app/models/good_job/batch_record.rb:4:in `<module:GoodJob>'
  from gems/3.2.0/gems/good_job-3.12.3/app/models/good_job/batch_record.rb:3:in `<main>'
```

No rush on my behalf, just for your information.

Love your work!

**Comment by mhenrixon** [comment]
```ruby
serialize :serialized_properties, coder: PropertySerializer
```

Seems to do the trick

**Comment by bensheldon** [comment]
Thanks @mhenrixon I was just poking at that 😁 I'll get a patch out momentarily.

**Comment by bensheldon** [comment]
Released 🙌🏻 https://github.com/bensheldon/good_job/releases/tag/v3.12.4

**Comment by mhenrixon** [comment]
Jesus you are fast! I was just going to clone the repo and provide a fix. Thanks a bunch!

**Comment by bensheldon** [comment]
lol! it was just the perfect chain of events. no promises in the future 😆
