### ISSUE TITLE
ArgumentError in GoodJob::Jobs#index

### ISSUE THREAD

**Issue by marcomarcianesi** [bensheldon/good_job#875]
Hello.
I'm trying out this gem, it looks awesome, but unfortunately there seems to be a small problem with rails 6

Rails 6.1.7 # This doesn't happen with rails 7.0.4
ruby 3.2.0

when trying to access the web interface, I get:

```
ArgumentError in GoodJob::Jobs#index
Showing /bundle/ruby/3.2.0/gems/good_job-3.12.7/app/views/good_job/jobs/index.html.erb where line #5 raised:

wrong number of arguments (given 1, expected 0)

[good_job (3.12.7) app/models/good_job/lockable.rb:75:in `block (2 levels) in <module:Lockable>'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:411:in `instance_exec'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:411:in `block in _exec_scope'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:804:in `_scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:411:in `_exec_scope'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/scoping/named.rb:176:in `block in scope'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation/delegation.rb:67:in `block in joins_advisory_locks'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:406:in `block in scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:804:in `_scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:406:in `scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation/delegation.rb:67:in `joins_advisory_locks'](http://background.kyero.test/good_job/jobs#)
[good_job (3.12.7) app/models/good_job/lockable.rb:93:in `block (2 levels) in <module:Lockable>'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:411:in `instance_exec'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:411:in `block in _exec_scope'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:804:in `_scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:411:in `_exec_scope'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/scoping/named.rb:176:in `block in scope'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation/delegation.rb:67:in `block in includes_advisory_locks'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:406:in `block in scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:804:in `_scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation.rb:406:in `scoping'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/relation/delegation.rb:67:in `includes_advisory_locks'](http://background.kyero.test/good_job/jobs#)
[good_job (3.12.7) app/filters/good_job/jobs_filter.rb:51:in `query_for_records'](http://background.kyero.test/good_job/jobs#)
[good_job (3.12.7) app/filters/good_job/base_filter.rb:17:in `records'](http://background.kyero.test/good_job/jobs#)
[good_job (3.12.7) app/views/good_job/jobs/index.html.erb:5](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/base.rb:247:in `public_send'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/base.rb:247:in `_run'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/template.rb:154:in `block in render'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications.rb:205:in `instrument'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/template.rb:345:in `instrument_render_template'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/template.rb:152:in `render'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `block in instrument'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `instrument'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `block in instrument'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `instrument'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/template_renderer.rb:55:in `render_template'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/template_renderer.rb:11:in `render'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/renderer/renderer.rb:29:in `render_to_object'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/rendering.rb:117:in `block in _render_template'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/base.rb:273:in `in_rendering_context'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/rendering.rb:116:in `_render_template'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/streaming.rb:218:in `_render_template'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/rendering.rb:103:in `render_to_body'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/rendering.rb:52:in `render_to_body'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/renderers.rb:142:in `render_to_body'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/abstract_controller/rendering.rb:25:in `render'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/rendering.rb:36:in `render'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'](http://background.kyero.test/good_job/jobs#)
[/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/core_ext/benchmark.rb:14:in `ms'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:46:in `block in render'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:45:in `render'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/implicit_render.rb:35:in `default_render'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'](http://background.kyero.test/good_job/jobs#)
[<internal:kernel>:90:in `tap'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/abstract_controller/base.rb:228:in `process_action'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/rendering.rb:30:in `process_action'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/abstract_controller/callbacks.rb:42:in `block in process_action'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:117:in `block in run_callbacks'](http://background.kyero.test/good_job/jobs#)
[i18n (1.12.0) lib/i18n.rb:322:in `with_locale'](http://background.kyero.test/good_job/jobs#)
[good_job (3.12.7) app/controllers/good_job/application_controller.rb:34:in `switch_locale'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'](http://background.kyero.test/good_job/jobs#)
[sentry-raven (3.1.2) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:126:in `instance_exec'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:137:in `run_callbacks'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/abstract_controller/callbacks.rb:41:in `process_action'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/rescue.rb:22:in `process_action'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `block in instrument'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/notifications.rb:203:in `instrument'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/instrumentation.rb:33:in `process_action'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/railties/controller_runtime.rb:27:in `process_action'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/abstract_controller/base.rb:165:in `process'](http://background.kyero.test/good_job/jobs#)
[actionview (6.1.7) lib/action_view/rendering.rb:39:in `process'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal.rb:190:in `dispatch'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_controller/metal.rb:254:in `dispatch'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:33:in `serve'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `each'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `serve'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:842:in `call'](http://background.kyero.test/good_job/jobs#)
[railties (6.1.7) lib/rails/engine.rb:539:in `call'](http://background.kyero.test/good_job/jobs#)
[railties (6.1.7) lib/rails/railtie.rb:207:in `public_send'](http://background.kyero.test/good_job/jobs#)
[railties (6.1.7) lib/rails/railtie.rb:207:in `method_missing'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/routing/mapper.rb:49:in `serve'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `each'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/journey/router.rb:32:in `serve'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/routing/route_set.rb:842:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/tempfile_reaper.rb:15:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/etag.rb:27:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/conditional_get.rb:27:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/head.rb:12:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/http/permissions_policy.rb:22:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/http/content_security_policy.rb:19:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/session/abstract/id.rb:266:in `context'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/session/abstract/id.rb:260:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/cookies.rb:689:in `call'](http://background.kyero.test/good_job/jobs#)
[activerecord (6.1.7) lib/active_record/migration.rb:601:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/callbacks.rb:98:in `run_callbacks'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'](http://background.kyero.test/good_job/jobs#)
[railties (6.1.7) lib/rails/rack/logger.rb:37:in `call_app'](http://background.kyero.test/good_job/jobs#)
[railties (6.1.7) lib/rails/rack/logger.rb:26:in `block in call'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/tagged_logging.rb:37:in `tagged'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/tagged_logging.rb:99:in `tagged'](http://background.kyero.test/good_job/jobs#)
[railties (6.1.7) lib/rails/rack/logger.rb:26:in `call'](http://background.kyero.test/good_job/jobs#)
[sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/method_override.rb:24:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/runtime.rb:22:in `call'](http://background.kyero.test/good_job/jobs#)
[activesupport (6.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/static.rb:24:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/sendfile.rb:110:in `call'](http://background.kyero.test/good_job/jobs#)
[actionpack (6.1.7) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'](http://background.kyero.test/good_job/jobs#)
[sentry-raven (3.1.2) lib/raven/integrations/rack.rb:51:in `call'](http://background.kyero.test/good_job/jobs#)
[railties (6.1.7) lib/rails/engine.rb:539:in `call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/urlmap.rb:74:in `block in call'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/urlmap.rb:58:in `each'](http://background.kyero.test/good_job/jobs#)
[rack (2.2.5) lib/rack/urlmap.rb:58:in `call'](http://background.kyero.test/good_job/jobs#)
[puma (6.0.2) lib/puma/configuration.rb:268:in `call'](http://background.kyero.test/good_job/jobs#)
[puma (6.0.2) lib/puma/request.rb:93:in `block in handle_request'](http://background.kyero.test/good_job/jobs#)
[puma (6.0.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://background.kyero.test/good_job/jobs#)
[puma (6.0.2) lib/puma/request.rb:92:in `handle_request'](http://background.kyero.test/good_job/jobs#)
[puma (6.0.2) lib/puma/server.rb:429:in `process_client'](http://background.kyero.test/good_job/jobs#)
[puma (6.0.2) lib/puma/server.rb:232:in `block in run'](http://background.kyero.test/good_job/jobs#)
[puma (6.0.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://background.kyero.test/good_job/jobs#)
```

**Comment by bensheldon** [comment]
Unfortunately, Rails 6.1 is not compatible with Ruby 3.2. There are some more details in https://github.com/bensheldon/good_job/issues/785 (I just renamed the title to be more findable).

**Comment by marcomarcianesi** [comment]
Thanks. Closing
