### ISSUE TITLE
Deprecation warning on the deprecation warning

### ISSUE THREAD

**Issue by zarqman** [bensheldon/good_job#943]
FYI, on Rails 7.1 (on commit `912096d4ce93`, which is HEAD as of now) with a pending GoodJob migration (such as the one just added in the 3.15.x series), I'm seeing the following deprecation warning about a change in ActiveSupport regarding deprecation warnings themselves:

```
ActiveSupport::DeprecationException: DEPRECATION WARNING: Calling warn on ActiveSupport::Deprecation is deprecated and will be removed from Rails (use your own Deprecation object instead) (called from migration_pending_warning! at ~/.rvm/gems/ruby-3.1.3@rails71/gems/good_job-3.15.6/app/models/good_job/base_record.rb:11)
~/.rvm/gems/ruby-3.1.3@rails71/bundler/gems/rails-912096d4ce93/activesupport/lib/active_support/deprecation/instance_delegator.rb:36:in `warn'
~/.rvm/gems/ruby-3.1.3@rails71/bundler/gems/rails-912096d4ce93/activesupport/lib/active_support/deprecation/instance_delegator.rb:50:in `warn'
~/.rvm/gems/ruby-3.1.3@rails71/gems/good_job-3.15.6/app/models/good_job/base_record.rb:11:in `migration_pending_warning!'
```

Reproducible in the Rails 7.1 console with:
```ruby
ActiveSupport::Deprecation.warn('test')
```

**Comment by bensheldon** [comment]
@zarqman thank you! I think I can get that fixed real easy.
