### ISSUE TITLE
Rails API dies when using latest good_job version

### ISSUE THREAD

**Issue by andreas-it-dev** [bensheldon/good_job#952]
Hi,

after upgrading it first complained about a missing sass compuler and after giving it that, it ends up with that error:

```
03:59:56 backend.1 | => Booting Puma
03:59:56 backend.1 | => Rails 7.0.4.3 application starting in development 
03:59:56 backend.1 | => Run `bin/rails server --help` for more startup options
03:59:56 worker.1  | /home/andreas/.rvm/gems/ruby-3.2.2/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:110:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
03:59:56 worker.1  | But did not, please create this file and use it to link any assets that need
03:59:56 worker.1  | to be rendered by your app:
03:59:56 worker.1  | 
03:59:56 worker.1  | Example:
03:59:56 worker.1  |   //= link_tree ../images
03:59:56 worker.1  |   //= link_directory ../javascripts .js
03:59:56 worker.1  |   //= link_directory ../stylesheets .css
03:59:56 worker.1  | and restart your server
03:59:56 worker.1  | 
03:59:56 worker.1  | For more information see: https://github.com/rails/sprockets/blob/070fc01947c111d35bb4c836e9bb71962a8e0595/UPGRADING.md#manifestjs
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
03:59:56 worker.1  | 	from /home/andreas/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
03:59:56 worker.1  | 	from /home/andreas/dev/web/vue_3_rails_api_template/backend/config/environment.rb:5:in `<top (required)>'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/good_job-3.15.7/lib/good_job/cli.rb:150:in `require'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/good_job-3.15.7/lib/good_job/cli.rb:150:in `set_up_application!'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/good_job-3.15.7/lib/good_job/cli.rb:92:in `start'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/gems/good_job-3.15.7/exe/good_job:7:in `<top (required)>'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/bin/good_job:25:in `load'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/bin/good_job:25:in `<main>'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
03:59:56 worker.1  | 	from /home/andreas/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'
03:59:56 backend.1 | Exiting
```

so, it really wants frontend stuff for whatever reason.

i am running a rails api only and wanted to use good job as my scheduler and obviously use its builtin frontend without using any rails frontend whatsoever. that worked just fine until recently.

is there some trick for me to perform in order to still be able to use good_job with a rails api only app?

thanks!

**Comment by bensheldon** [comment]
That's unexpected! GoodJob shouldn't have any dependencies on sprockets so I'm surprised to see that in there. It looks like more that `Rails` is failing to initialize itself more so than GoodJob is erroring even though you're running the GoodJob `cli` (the stacktrace says that exception is being raised in the `sprockets-rails` initializer). Are you able to successfully run `bin/rails s` but just `bin/good_job` errors?

Did you upgrade _just_ GoodJob or did you upgrade other gems as well (`rails`, `sprockets`, `sprockets-rails`)? I wonder if one of them became more aggressive with checking for the manifest file.

So while I don't think this is specific to GoodJob, I think you will need to:

- Remove `sprockets-rails`/`sprockets`, because I think it now demands a manifest file.
- Or, add a manifest file to appease Sprockets.
