### ISSUE TITLE
A copy of GoodJob::Execution has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by isaac** [bensheldon/good_job#954]
Anyone ever come across this exception?

```
[GoodJob] GoodJob error: ArgumentError: A copy of GoodJob::Execution has been removed from the module tree but is still active!
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:543:in `load_missing_constant'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:213:in `const_missing'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:347:in `rescue in block (3 levels) in perform'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:331:in `block (3 levels) in perform'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sentry-rails-5.3.1/lib/sentry/rails/tracing.rb:54:in `instrument'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `instrument'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:330:in `block (2 levels) in perform'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/lib/good_job/current_thread.rb:91:in `within'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:323:in `block in perform'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/batch.rb:75:in `within_thread'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:440:in `reset_batch_values'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:320:in `perform'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:260:in `block in perform_with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/lockable.rb:164:in `block in with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/scoping/default.rb:34:in `block in unscoped'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `block in scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:804:in `_scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/scoping/default.rb:34:in `unscoped'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/lockable.rb:164:in `with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation/delegation.rb:67:in `block in with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `block in scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:804:in `_scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation/delegation.rb:67:in `with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/app/models/good_job/execution.rb:254:in `perform_with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation/delegation.rb:67:in `block in perform_with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `block in scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:804:in `_scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation.rb:406:in `scoping'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6/lib/active_record/relation/delegation.rb:67:in `perform_with_advisory_lock'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/lib/good_job/job_performer.rb:30:in `next'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/lib/good_job/scheduler.rb:289:in `block (2 levels) in create_task'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:71:in `wrap'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-3.15.0/lib/good_job/scheduler.rb:288:in `block in create_task'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/ivar.rb:169:in `safe_execute'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/timer_set.rb:98:in `block in ns_post_task'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/Users/isaac/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

Some details about my environment below.

OS: macOS Ventura 13.3.1
Rails: 6.1.6
Ruby 3.1.2
GoodJob 3.15.0

**Comment by bensheldon** [comment]
@isaac hmm, that's a new one to me for GoodJob! I've seen that error before on other projects, which is a sign of autoloading problems. 

Can you try running `bin/rails zeitwerk:check`? That _might_ help uncover an autoloading problem somewhere else in your application that is just manifesting over here.

**Comment by bensheldon** [comment]
I should also ask, are you referencing `GoodJob::Execution` somewhere else in your application code (possibly to update the database configuration or something in an initializer?)

**Comment by henrydjacob** [comment]
I am facing the same problem, any solution?
